djangosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^practice/', include('practice.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_views.index_view,name='home_index'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^add/$', views.add, name='add'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^myvote/$', views.myvote_view, name='myvote'),
    url(r'^myquestion/$', views.myquestion_view, name='myquestion'),
    url(r'^profile/$', views.profile_view, name='profile'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
DEFAULT_USER_ID = 2

# todo user profile
# class UserProfile(models.Model):
#     user = models.OneToOneField(User)
#
#     def __str__(self):
#         return '<%s>' % self.user.get_username()


class Question(models.Model):
    error_css_class = 'error'
    question_text = models.CharField('Question',max_length=200)
    pub_date = models.DateTimeField('date published')
    owner = models.ForeignKey(User,default=DEFAULT_USER_ID)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return '<%s>' % self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return '<%s>' % self.question


class Vote(models.Model):
    choice = models.ForeignKey(Choice)
    voter = models.ForeignKey(User,default=DEFAULT_USER_ID)
    vote_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<%s, voter:%s>' % (self.choice, self.voter)


class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name="profile")
    username = models.CharField(max_length=100)
    birthday = models.DateField()

    def __str__(self):
        return self.username

polls/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from .models import Choice, Question, Vote, UserProfile
from django.db.models import Sum
from django.contrib import messages
from .form import RegisterForm


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        myvote={}
        myvote['choice'] = selected_choice
        if request.user.id:
            myvote['voter'] = request.user
        mynewvote = Vote(**myvote)
        mynewvote.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def add(request):
    if request.method == 'POST':
        content = request.POST
        print(content)
        allChoice = []
        for i in content.getlist('choice'):
            if i != '':
                allChoice.append(i)
        if content['question'] and allChoice:
            question = {}
            question['question_text'] = content['question']
            question['pub_date'] = timezone.now()
            # print(type(request.user))
            if request.user.id:
                question['owner'] = request.user

            newQuestion = Question(**question)
            newQuestion.save()


            for temp in allChoice:
                if temp != '' and temp!= None:

                    # print(type(Choice.choice_text))
                    choice = {}
                    choice['question'] = newQuestion
                    choice['choice_text'] = temp
                    choice['votes'] = 0
                    newChoice = Choice(**choice)
                    newChoice.save()

            latest_question_list = Question.objects.order_by('-pub_date')
            add_status = 1
            return render(request, 'polls/add.html',{'add_status':add_status})
        else:
            add_status = -1
            return render(request, 'polls/add.html',{'add_status':add_status})
    return render(request, 'polls/add.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/polls')

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        # todo email check
        login(request, user)
        messages.success(request, "Welcome "+ user.get_username())
        return HttpResponseRedirect('/polls')
    else:
        content={}
        content['err_msg']='Username or Password Error!'
        content['latest_question_list']=Question.objects.order_by('-pub_date')
        # print(content)
        return render(request, 'polls/index.html',content)


def signup_view(request):
    if request.user.is_authenticated:
        return redirect('/profile/')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],email=form.cleaned_data['email'],
                                            password=form.cleaned_data['password'],first_name=form.cleaned_data['firstname'],
                                            last_name=form.cleaned_data['lastname'])
            user.save()
            userprofile = UserProfile(user=user,birthday=form.cleaned_data['birthday'])
            userprofile.save()
            login(request, user)
            return HttpResponseRedirect('polls/profile/')
        else:
            return render(request,'polls/signup.html',{'form':form})
    else:
        form = RegisterForm()
        context = {'form':form}
        return render(request,'polls/signup.html',context)


def myvote_view(request):
    all_votes = Vote.objects.filter(voter=request.user.id).annotate(total_votes=Sum('choice__votes'))
    
    return render(request, 'polls/myvote.html',{'all_votes':all_votes})


def myquestion_view(request):
    all_questions = Question.objects.filter(owner_id=request.user.id).annotate(total_votes=Sum('choice__votes')).values()

    return render(request, 'polls/myquestion.html',{'all_questions':all_questions})


def profile_view(request):
    all_votes = Vote.objects.filter(voter=request.user.id).all()
    return render(request, 'polls/profile.html',{'all_votes':all_votes})

# todo reset password through email

polls/templates/polls/add.html
{% extends 'polls/base.html' %}
{% block head %}
{#    <script type="text/javascript" src="static/bs/jquery-3.1.1.min.js"></script>#}

{% endblock %}
{% block content %}

    <div style="margin:0 auto;width:500px;margin-top: 100px;line-height:30px;">
        {% if add_status == -1 %}
            <div class="alert alert-danger" role="alert" style="margin-bottom: 5px;">
                <strong>Error!</strong>
            </div>
        {% elif add_status == 1 %}
            <div class="alert alert-success" role="alert" style="margin-bottom: 5px;">
                <strong>Success!</strong>
            </div>
        {% endif %}
        <form method="post" action="{% url 'polls:add' %}">{% csrf_token %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Question</h3>
                </div>

            </div>


            <textarea name="question" class="form-control" style="height: 100px;margin-bottom: 20px"></textarea>

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Choice</h3>
                </div>

            </div>

            <input name="choice" type="text" class="form-control" style="margin-top: 10px">
            <input name="choice" type="text" class="form-control" style="margin-top: 10px">
            <input name="choice" type="text" class="form-control" style="margin-top: 10px">
            <input name="choice" type="text" class="form-control" style="margin-top: 10px">
            <input name="choice" type="text" class="form-control" style="margin-top: 10px">


            <a href="{% url 'polls:index' %}">
                <button type="button" class="btn btn-success" style="margin-top: 20px;float:left;width: 80px;">Home
                </button>
            </a>
{#            <button type="button" onclick="addButton()" class="btn btn-info" style="margin-top: 20px;float:left;margin-left: 10px;">Add#}
{#                choice#}
{#            </button>#}

            <button type="submit" class="btn btn-warning" style="margin-top: 20px;float:right;">Submit</button>
        </form>
    </div>
{% endblock %}
{% block last %}
{#        <script>#}
{#            function addButton() {#}
{#                var obj = '<input name="choice" type="text" class="form-control" style="margin-top: 10px">';#}
{#                $("#myinput").append(obj);#}
{#            }#}
{#        </script>#}
{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bs/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav" style="float: right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'polls:profile' %}">Profile</a></li>
                            <li><a href="{% url 'polls:myquestion' %}">My Question</a></li>
                            <li><a href="{% url 'polls:myvote' %}">My Vote</a></li>
                            <li role="separator" class="divider"></li>
                            {#                <li class="dropdown-header">Nav header</li>#}
                            <li><a href="{% url 'polls:logout' %}">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <!--not au -->
                <form class="navbar-form navbar-right" method="post" action="{% url 'polls:login' %}">{% csrf_token %}
                    <div class="form-group">
                        <input name="username" type="text" placeholder="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <input name="password" type="password" placeholder="Password" class="form-control">
                    </div>


                    <button type="submit" class="btn btn-success">Sign in</button>

                    <a href="{% url 'polls:signup' %}">

                        <button type="button" class="btn btn-success">Sign up</button>
                    </a>
                </form>
            {% endif %}
            <!--end -->

        </div><!--/.navbar-collapse -->
    </div>
</nav>

<div class="wrapper" style="position: relative;margin-top: 0px;">
    {% if err_msg %}
        <div style="left: 50%; margin-left: -250px;;width:500px;margin-top: -65px;line-height:30px;position: absolute;text-align: center; ">
            <div class="alert alert-danger" role="alert">
                <strong>{{ err_msg }}</strong>
            </div>
        </div>
    {% endif %}
    {% if messages %}
        {% for message in messages %}

            <div style="left: 50%; margin-left: -250px;;width:500px;margin-top: -65px;line-height:30px;position: absolute;text-align: center; ">
                <div class="alert alert-success" role="alert">
                    <strong>{{ message }}</strong>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
<!-- Bootstrap core JavaScript
================================================== -->

<script src="{% static 'bs/js/jquery.min.js' %}"></script>
<script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
{% block last %}
{% endblock %}
</body>

</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}

    <div class="panel panel-info" style="margin:0 auto;width:500px;margin-top: 100px;line-height:30px;">
        <div class="panel-heading">
            <b>{{ question.id }}. </b>{{ question.question_text }}
            <br>-- <i><b>author:</b></i> {{ question.owner.username }}  <i><b>date:</b></i> {{ question.pub_date }}
        </div>
        <div class="panel-body">
            {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error_message }}</strong>
                </div>
            {% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"
                           style="margin-right: 20px;"/>
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
                {% endfor %}
                <button type="submit" value="Vote" class="btn btn-default" style="margin-top:20px;width: 100px"><b>Vote</b></button>

            </form>
        </div>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block head %}
    {% load static %}

{% endblock %}
{% block content %}
    {% if signup_msg %}
        <div style="left: 50%; margin-left: -250px;;width:500px;margin-top: -65px;line-height:30px;position: absolute;text-align: center; ">
            <div class="alert alert-success" role="alert">
                <strong>{{ signup_msg }}</strong>
            </div>
        </div>
    {% endif %}

    <div class="list-group" style="margin:0 auto;width:500px;margin-top: 120px;line-height:30px;">
        <a class="list-group-item active">
            <h3 class="panel-title">
                <h4>Questions</h4>

            </h3>
        </a>


        {% if latest_question_list %}

            {% for question in latest_question_list reversed %}
                <a class="list-group-item"
                   href="{% url 'polls:detail' question.id %}"><b>{{ forloop.counter }}. </b>{{ question.question_text }}
                    <br>-- <i><b>author:</b></i> {{ question.owner.username }}  <i><b>date:</b></i> {{ question.pub_date }}
                </a>
            {% endfor %}

        {% else %}
            <div class="alert alert-danger" role="alert">
                <p>No polls are available.</p>
            </div>

        {% endif %}

        <a href="{% url 'polls:add' %}">
            <button type="button" class="btn btn-warning" style="margin-top: 20px;margin-bottom: 50px;">Add Question</button>
        </a>
    </div>

{% endblock %}

polls/templates/polls/myquestion.html
{% extends 'polls/base.html' %}

{% block content %}

    <div style="margin:0 auto;width: 800px;margin-top: 100px;">
        <h2 class="sub-header">My Question</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th style="text-align:center">Question Id</th>
                    <th>Question</th>
                    <th style="text-align:center">Total voter</th>
                    <th style="text-align:center">Date</th>
                </tr>
                </thead>
                <tbody>
                {% for content in all_questions %}
                <tr>
                    <td style="word-wrap:break-word;word-break:break-all;width: 100px;"><h4 style="text-align:center">{{ content.id }}</h4></td>
                    <td style="word-wrap:break-word;word-break:break-all;width: 500px;"><h5>{{ content.question_text }}</h5></td>
                    <td style="word-wrap:break-word;word-break:break-all;width: 100px;"><h5 style="text-align:center">{{ content.total_votes }}</h5></td>
                    <td style="word-wrap:break-word;word-break:break-all;width: 100px;"><h5 style="text-align:center">{{ content.pub_date }}</h5></td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

polls/templates/polls/myvote.html
{% extends 'polls/base.html' %}

{% block content %}
    <div style="margin:0 auto;width: 800px;margin-top: 100px;">
        <h2 class="sub-header">My Vote</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th >Question</th>
                    <th >My Vote</th>
                    <th style="text-align:center">Date</th>
                </tr>
                </thead>
                <tbody>
                {% for content in all_votes %}
                <tr>
                    <td style="word-wrap:break-word;word-break:break-all;width: 400px;"><h5>{{ content.choice.question.question_text }}</h5></td>
                    <td style="word-wrap:break-word;word-break:break-all;width: 300px;"><h5>{{ content.choice.choice_text }}</h5></td>
                    <td style="word-wrap:break-word;word-break:break-all;width: 100px;"><h5 style="text-align:center">{{ content.vote_date }}</h5></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

polls/templates/polls/profile.html
{% extends 'polls/base.html' %}

{% block content %}

    <h1 style="text-align:center;margin:0 auto;margin-top: 200px;">in progress</h1>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}

    <div class="panel panel-warning" style="margin:0 auto;width:500px;margin-top: 100px;line-height:30px;">
        <div class="panel-heading">
            <b>{{ question.id  }}. </b>{{ question.question_text }}
            <br>-- <i><b>author:</b></i> {{ question.owner.username }}  <i><b>date:</b></i> {{ question.pub_date }}
        </div>
        <div class="panel-body">
            {% for choice in question.choice_set.all %}
                <li><strong>{{ choice.choice_text }} -- <span class="badge">{{ choice.votes }}</span>
                    vote{{ choice.votes|pluralize }}</strong></li>
            {% endfor %}
        </div>
        <div class="panel-body">
            <a href="{% url 'polls:detail' question.id %}">
                <button type="button" class="btn btn-success">Vote again?</button>
            </a>


            <a href="{% url 'polls:index' %}">
                <button type="button" class="btn btn-primary" style="width: 100px">Home</button>
            </a>
        </div>
    </div>

{% endblock %}

polls/templates/polls/signup.html
{% extends 'polls/base.html' %}
{% block content %}
    <div class="container" style="width: 300px; margin-top: 120px;">

        <form class="form-signin" method="post" action="{% url 'polls:signup' %}">{% csrf_token %}
            <h2 class="form-signin-heading">Please sign up</h2>
{#            <label for="inputUsername" class="sr-only">Username</label>#}
{#            <input type="" name="inputUsername" class="form-control" placeholder="Username" required=""#}
{#                   autofocus="" style="margin-bottom: 10px">#}
{##}
{#            <label for="inputEmail" class="sr-only">Email</label>#}
{#            <input type="email" name="inputEmail" class="form-control" placeholder="Email Address" required=""#}
{#                   autofocus="" style="margin-bottom: 10px">#}
{##}
{##}
{#            <label for="inputPassword" class="sr-only">Password</label>#}
{#            <input type="password" name="inputPassword1" class="form-control" placeholder="Password" required=""#}
{#                   style="margin-bottom: 10px">#}
{#            <input type="password" name="inputPassword2" class="form-control" placeholder="Password Again" required=""#}
{#                   style="margin-bottom: 10px">#}
{#            {{ form }}#}
                {% if form.errors %}<p>please correct the following fields:</p>{% endif %}
                {% if form.username.errors %}<p class="text-danger">{{ form.username.errors }}</p>{% endif %}
                {{ form.username }}
                {% if form.email.errors %}<p class="text-danger">{{ form.email.errors }}</p>{% endif %}
                {{ form.email }}
                {% if form.firstname.errors %}<p class="text-danger">{{ form.firstname.errors }}</p>{% endif %}
                {{ form.firstname }}
                {% if form.lastname.errors %}<p class="text-danger">{{ form.lastname.errors }}</p>{% endif %}
                {{ form.lastname }}
                {% if form.birthday.errors %}<p class="text-danger">{{ form.birthday.errors }}</p>{% endif %}
                {{ form.birthday }}
                {% if form.password.errors %}<p class="text-danger">{{ form.password.errors }}</p>{% endif %}
                {{ form.password }}
                {% if form.password1.errors %}<p class="text-danger">{{ form.password1.errors }}</p>{% endif %}
                {{ form.password1 }}

            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        </form>



    </div>
{% endblock %}

polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="http://code.jquery.com/jquery-1.8.0.min.js">
   var max_fields      = 5; //maximum input boxes allowed
    var wrapper          = $(".input_fields_wrap"); //Fields wrapper
    var add_button    =(".add_field_button"); //Add button ID

    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<tr style=""><td></td><td><button  class="remove_field btn">Del</button></td></tr>'); //add input box
            }
    });

    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).closest('tr').remove(); x--;
    })
</script>
</head>
<body>

    <tr><button style="margin-left:10px" class="add_field_button btn">Add</button></tr>
    <tbody class="input_fields_wrap"></tbody>

</body>
</html>